name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Package with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t backendapp:v1 .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag backendapp:v1 bhanu165/backendapp:v1
          docker push bhanu165/backendapp:v1

      - name: Deploy on Ubuntu1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull bhanu165/backendapp:v1
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend --restart always -p 8080:8080 bhanu165/backendapp:v1
